/* The following code was generated by JFlex 1.7.0 */

package Analisis.Fs;
import java_cup.runtime.Symbol;
import java.util.ArrayList;
import Recursos.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>scannerfs.flex</tt>
 */
public class scannerfs implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int comentarioSimple = 2;
  public static final int comentarioMulti = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
    10, 10, 10, 10, 10, 10, 10, 10, 10,  1,  8, 57,  1,  2, 10, 10, 
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
     1, 29,  9, 10, 10, 10, 28, 15, 33, 34, 17, 24, 38, 25,  4, 16, 
     3,  3,  3,  3,  3,  3,  3,  3,  3,  3, 56, 49, 32, 30, 31, 37, 
    10, 40,  5, 48, 46, 44, 47,  5, 53, 21,  5,  5, 43, 50, 22, 23, 
    51,  5, 41, 19, 45, 42, 39, 52,  5,  5,  5, 35, 10, 36, 26,  5, 
    10, 40,  5, 48, 46, 44, 47,  5, 53, 21,  5,  5, 43, 50, 22, 23, 
    51,  5, 41, 19, 45, 42, 39, 52,  5,  5,  5, 54, 27, 55, 10, 10, 
    10, 10, 10, 10, 10, 57, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
    10,  7, 10, 10, 10, 10, 10, 10, 10,  7, 10, 10, 10,  7, 10, 10, 
    10,  7, 10,  7, 10, 10, 10, 10, 10, 10,  7, 10, 10, 10, 10, 10, 
    10, 10, 11,  6, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
    10, 10, 11,  6, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\3\1\1\7\1\10\1\1\1\5\1\1\2\5\1\11"+
    "\1\12\1\13\2\1\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\5\5\1\26\1\5"+
    "\1\27\1\30\1\31\5\0\1\32\1\0\1\33\1\34"+
    "\1\35\2\0\1\35\2\5\1\0\2\5\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\12\5\1\50\1\51\1\0\1\52\2\32\4\0\3\5"+
    "\1\0\2\5\1\53\4\5\1\54\3\5\1\0\1\5"+
    "\1\0\1\5\1\0\1\55\2\0\1\55\2\5\1\0"+
    "\1\5\1\56\4\5\1\0\3\5\2\57\1\0\1\5"+
    "\3\0\2\5\1\0\5\5\2\60\1\0\1\5\1\0"+
    "\1\5\2\61\2\0\1\62\1\5\1\62\1\0\5\5"+
    "\1\0\1\5\1\0\1\5\1\0\1\5\1\0\3\5"+
    "\1\63\1\64\2\65\1\0\1\5\1\0\1\5\2\66"+
    "\1\5\1\67\2\70\1\0\1\5\1\71\2\72";

  private static int [] zzUnpackAction() {
    int [] result = new int[192];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\73\0\73\0\166\0\73\0\261\0\354"+
    "\0\73\0\u0127\0\u0162\0\u019d\0\u01d8\0\u0213\0\u024e\0\u0289"+
    "\0\u02c4\0\u02ff\0\u033a\0\u0375\0\u03b0\0\73\0\u03eb\0\u0426"+
    "\0\u0461\0\u049c\0\u04d7\0\u0512\0\73\0\73\0\73\0\73"+
    "\0\73\0\73\0\u054d\0\u0588\0\u05c3\0\u05fe\0\u0639\0\73"+
    "\0\u0674\0\73\0\73\0\73\0\u06af\0\354\0\u06ea\0\u0725"+
    "\0\u0760\0\u079b\0\u07d6\0\73\0\73\0\u0811\0\u084c\0\u0887"+
    "\0\u08c2\0\u08fd\0\u0938\0\u0973\0\u09ae\0\u09e9\0\73\0\73"+
    "\0\73\0\73\0\73\0\73\0\73\0\73\0\73\0\73"+
    "\0\u0a24\0\u0a5f\0\u0a9a\0\u0ad5\0\u0b10\0\u0b4b\0\u0b86\0\u0bc1"+
    "\0\u0bfc\0\u0c37\0\u06af\0\73\0\u0c72\0\73\0\u0cad\0\73"+
    "\0\u0ce8\0\u0d23\0\u0d5e\0\u0d99\0\u0dd4\0\u0e0f\0\u0e4a\0\u0e85"+
    "\0\u0ec0\0\u0efb\0\261\0\u0f36\0\u0f71\0\u0fac\0\u0fe7\0\261"+
    "\0\u1022\0\u105d\0\u1098\0\u10d3\0\u110e\0\u1149\0\u1184\0\u11bf"+
    "\0\73\0\u11fa\0\u1235\0\261\0\u1270\0\u12ab\0\u12e6\0\u1321"+
    "\0\261\0\u135c\0\u1397\0\u13d2\0\u140d\0\u1448\0\u1483\0\u14be"+
    "\0\u14f9\0\73\0\261\0\u1534\0\u156f\0\u15aa\0\u15e5\0\u1620"+
    "\0\u165b\0\u1696\0\u16d1\0\u170c\0\u1747\0\u1782\0\u17bd\0\u17f8"+
    "\0\73\0\261\0\u1833\0\u186e\0\u18a9\0\u18e4\0\73\0\261"+
    "\0\u191f\0\u195a\0\73\0\u1995\0\261\0\u19d0\0\u1a0b\0\u1a46"+
    "\0\u1a81\0\u1abc\0\u1af7\0\u1b32\0\u1b6d\0\u1ba8\0\u1be3\0\u1c1e"+
    "\0\u1c59\0\u1c94\0\u1ccf\0\u1d0a\0\u1d45\0\261\0\261\0\73"+
    "\0\261\0\u1d80\0\u1dbb\0\u1df6\0\u1e31\0\73\0\261\0\u1e6c"+
    "\0\261\0\73\0\261\0\u1ea7\0\u1ee2\0\261\0\73\0\261";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[192];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\6\1\7\1\10\1\3\1\11"+
    "\1\12\1\3\1\13\3\3\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\7\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\7\1\44\4\7"+
    "\1\45\1\46\1\47\1\50\2\7\1\51\1\7\1\52"+
    "\1\53\1\54\100\0\1\5\1\55\71\0\1\7\1\0"+
    "\1\7\1\56\14\0\1\7\1\0\3\7\17\0\12\7"+
    "\1\0\4\7\14\0\1\7\64\0\13\57\3\0\3\57"+
    "\1\0\1\57\1\0\45\57\15\0\1\60\57\0\13\61"+
    "\3\0\3\61\1\0\1\61\1\0\45\61\21\0\1\62"+
    "\1\63\14\0\1\64\72\0\1\65\60\0\2\66\26\0"+
    "\1\67\7\0\1\70\11\0\1\7\1\0\1\7\1\56"+
    "\14\0\1\7\1\66\1\71\2\7\17\0\5\7\1\72"+
    "\4\7\1\0\2\7\1\73\1\7\67\0\1\74\13\0"+
    "\1\7\1\0\1\7\1\56\14\0\1\7\1\0\3\7"+
    "\17\0\12\7\1\0\1\75\3\7\10\0\1\7\1\0"+
    "\1\7\1\56\14\0\1\7\1\0\3\7\17\0\3\7"+
    "\1\76\6\7\1\0\4\7\35\0\1\77\5\0\1\100"+
    "\65\0\1\101\4\0\1\102\67\0\1\103\73\0\1\104"+
    "\74\0\1\105\72\0\1\106\72\0\1\107\72\0\1\110"+
    "\37\0\1\7\1\0\1\7\1\56\14\0\1\7\1\0"+
    "\3\7\17\0\1\7\1\111\3\7\1\112\4\7\1\0"+
    "\4\7\10\0\1\7\1\0\1\7\1\56\14\0\1\7"+
    "\1\0\3\7\17\0\5\7\1\113\4\7\1\0\4\7"+
    "\10\0\1\7\1\0\1\7\1\56\14\0\1\7\1\0"+
    "\3\7\17\0\5\7\1\114\4\7\1\0\4\7\10\0"+
    "\1\7\1\0\1\7\1\56\14\0\1\7\1\0\2\7"+
    "\1\115\17\0\1\7\1\116\1\7\1\117\6\7\1\0"+
    "\4\7\10\0\1\7\1\0\1\7\1\56\14\0\1\7"+
    "\1\0\2\7\1\120\17\0\1\7\1\121\10\7\1\0"+
    "\4\7\10\0\1\7\1\0\1\7\1\56\14\0\1\7"+
    "\1\0\3\7\17\0\12\7\1\0\3\7\1\122\10\0"+
    "\1\123\67\0\11\57\1\124\61\57\15\0\1\125\55\0"+
    "\17\61\1\126\53\61\2\62\1\127\5\62\1\130\62\62"+
    "\21\63\1\131\51\63\26\0\1\132\117\0\1\133\43\0"+
    "\2\134\50\0\1\7\1\0\1\7\1\56\14\0\1\7"+
    "\1\0\1\7\1\135\1\7\17\0\12\7\1\0\4\7"+
    "\10\0\1\7\1\0\1\7\1\56\14\0\1\7\1\0"+
    "\3\7\17\0\4\7\1\136\5\7\1\0\4\7\10\0"+
    "\1\7\1\0\1\7\1\56\14\0\1\7\1\134\1\137"+
    "\2\7\17\0\12\7\1\0\4\7\70\0\1\140\12\0"+
    "\1\7\1\0\1\7\1\56\14\0\1\7\1\0\3\7"+
    "\17\0\12\7\1\0\1\7\1\141\2\7\10\0\1\7"+
    "\1\0\1\7\1\56\14\0\1\7\1\0\3\7\17\0"+
    "\4\7\1\142\5\7\1\0\4\7\10\0\1\7\1\0"+
    "\1\7\1\56\14\0\1\7\1\0\3\7\17\0\2\7"+
    "\1\143\7\7\1\0\4\7\10\0\1\7\1\0\1\7"+
    "\1\56\14\0\1\7\1\0\3\7\17\0\2\7\1\144"+
    "\7\7\1\0\4\7\10\0\1\7\1\0\1\7\1\56"+
    "\14\0\1\7\1\0\3\7\17\0\6\7\1\145\3\7"+
    "\1\0\4\7\10\0\1\7\1\0\1\7\1\56\14\0"+
    "\1\7\1\0\3\7\17\0\6\7\1\146\1\7\1\147"+
    "\1\7\1\0\4\7\10\0\1\7\1\0\1\7\1\56"+
    "\14\0\1\7\1\0\3\7\17\0\2\7\1\150\7\7"+
    "\1\0\4\7\10\0\1\7\1\0\1\7\1\56\14\0"+
    "\1\7\1\0\3\7\17\0\4\7\1\151\5\7\1\0"+
    "\4\7\10\0\1\7\1\0\1\7\1\56\14\0\1\7"+
    "\1\0\1\7\1\152\1\7\17\0\12\7\1\0\4\7"+
    "\10\0\1\7\1\0\1\7\1\56\14\0\1\7\1\0"+
    "\1\7\1\153\1\7\17\0\12\7\1\0\4\7\10\0"+
    "\1\7\1\0\1\7\1\56\13\0\1\154\1\155\1\0"+
    "\3\7\17\0\12\7\1\0\4\7\10\0\1\7\1\0"+
    "\1\7\1\56\14\0\1\7\1\156\1\157\2\7\17\0"+
    "\12\7\1\0\4\7\6\0\13\160\3\0\3\160\1\0"+
    "\1\160\1\0\45\160\11\0\1\130\62\0\20\63\1\130"+
    "\1\131\51\63\27\0\1\161\117\0\1\162\73\0\1\163"+
    "\20\0\1\7\1\0\1\7\1\56\14\0\1\7\1\0"+
    "\2\7\1\164\17\0\12\7\1\0\4\7\10\0\1\7"+
    "\1\0\1\7\1\56\14\0\1\7\1\0\3\7\17\0"+
    "\5\7\1\165\4\7\1\0\4\7\10\0\1\7\1\0"+
    "\1\7\1\56\14\0\1\7\1\0\3\7\17\0\6\7"+
    "\1\166\3\7\1\0\4\7\56\0\1\167\24\0\1\7"+
    "\1\0\1\7\1\56\14\0\1\7\1\0\3\7\17\0"+
    "\2\7\1\170\7\7\1\0\4\7\10\0\1\7\1\0"+
    "\1\7\1\56\14\0\1\7\1\0\2\7\1\171\17\0"+
    "\12\7\1\0\4\7\10\0\1\7\1\0\1\7\1\56"+
    "\14\0\1\7\1\0\3\7\17\0\7\7\1\172\2\7"+
    "\1\0\4\7\10\0\1\7\1\0\1\7\1\56\14\0"+
    "\1\7\1\0\2\7\1\173\17\0\12\7\1\0\4\7"+
    "\10\0\1\7\1\0\1\7\1\56\14\0\1\7\1\0"+
    "\3\7\17\0\5\7\1\174\4\7\1\0\4\7\10\0"+
    "\1\7\1\0\1\7\1\56\14\0\1\7\1\0\3\7"+
    "\17\0\5\7\1\175\4\7\1\0\4\7\10\0\1\7"+
    "\1\0\1\7\1\56\13\0\1\176\1\177\1\0\3\7"+
    "\17\0\12\7\1\0\4\7\10\0\1\7\1\0\1\7"+
    "\1\56\14\0\1\7\1\0\3\7\17\0\11\7\1\200"+
    "\1\0\4\7\10\0\1\7\1\0\1\7\1\56\14\0"+
    "\1\7\1\0\3\7\17\0\6\7\1\201\3\7\1\0"+
    "\4\7\34\0\1\202\46\0\1\7\1\0\1\7\1\56"+
    "\14\0\1\7\1\0\2\7\1\203\17\0\12\7\1\0"+
    "\4\7\60\0\1\204\22\0\1\7\1\0\1\7\1\56"+
    "\14\0\1\7\1\0\3\7\17\0\4\7\1\205\5\7"+
    "\1\0\4\7\5\0\13\160\1\206\57\160\60\0\1\207"+
    "\72\0\1\210\15\0\1\7\1\0\1\7\1\56\14\0"+
    "\1\7\1\0\3\7\17\0\11\7\1\211\1\0\4\7"+
    "\10\0\1\7\1\0\1\7\1\56\14\0\1\7\1\0"+
    "\3\7\17\0\11\7\1\212\1\0\4\7\31\0\2\213"+
    "\50\0\1\7\1\0\1\7\1\56\14\0\1\7\1\213"+
    "\1\214\2\7\17\0\12\7\1\0\4\7\10\0\1\7"+
    "\1\0\1\7\1\56\14\0\1\7\1\0\3\7\17\0"+
    "\1\7\1\215\10\7\1\0\4\7\10\0\1\7\1\0"+
    "\1\7\1\56\14\0\1\7\1\0\3\7\17\0\2\7"+
    "\1\216\7\7\1\0\4\7\10\0\1\7\1\0\1\7"+
    "\1\56\14\0\1\7\1\0\1\7\1\217\1\7\17\0"+
    "\12\7\1\0\4\7\10\0\1\7\1\0\1\7\1\56"+
    "\14\0\1\7\1\0\3\7\17\0\11\7\1\220\1\0"+
    "\4\7\34\0\1\221\46\0\1\7\1\0\1\7\1\56"+
    "\14\0\1\7\1\0\2\7\1\222\17\0\12\7\1\0"+
    "\4\7\10\0\1\7\1\0\1\7\1\56\14\0\1\7"+
    "\1\223\1\224\2\7\17\0\12\7\1\0\4\7\10\0"+
    "\1\7\1\0\1\7\1\56\14\0\1\7\1\225\1\226"+
    "\2\7\17\0\12\7\1\0\4\7\61\0\1\227\21\0"+
    "\1\7\1\0\1\7\1\56\14\0\1\7\1\0\3\7"+
    "\17\0\5\7\1\230\4\7\1\0\4\7\5\0\13\160"+
    "\1\206\1\231\56\160\60\0\1\232\77\0\1\233\10\0"+
    "\1\7\1\0\1\7\1\56\14\0\1\7\1\0\3\7"+
    "\17\0\11\7\1\234\1\0\4\7\10\0\1\7\1\0"+
    "\1\7\1\56\14\0\1\7\1\0\3\7\17\0\12\7"+
    "\1\0\3\7\1\235\67\0\1\236\13\0\1\7\1\0"+
    "\1\7\1\56\14\0\1\7\1\0\3\7\17\0\12\7"+
    "\1\0\1\237\3\7\10\0\1\7\1\0\1\7\1\56"+
    "\14\0\1\7\1\0\3\7\17\0\7\7\1\240\2\7"+
    "\1\0\4\7\10\0\1\7\1\0\1\7\1\56\14\0"+
    "\1\7\1\0\1\7\1\241\1\7\17\0\12\7\1\0"+
    "\4\7\10\0\1\7\1\0\1\7\1\56\14\0\1\7"+
    "\1\0\3\7\17\0\5\7\1\242\4\7\1\0\4\7"+
    "\10\0\1\7\1\0\1\7\1\56\14\0\1\7\1\0"+
    "\3\7\17\0\6\7\1\243\3\7\1\0\4\7\34\0"+
    "\1\244\46\0\1\7\1\0\1\7\1\56\14\0\1\7"+
    "\1\0\2\7\1\245\17\0\12\7\1\0\4\7\33\0"+
    "\1\246\47\0\1\7\1\0\1\7\1\56\14\0\1\7"+
    "\1\0\1\7\1\247\1\7\17\0\12\7\1\0\4\7"+
    "\5\0\13\160\1\206\2\160\1\124\54\160\24\0\2\250"+
    "\50\0\1\7\1\0\1\7\1\56\14\0\1\7\1\250"+
    "\1\251\2\7\17\0\12\7\1\0\4\7\31\0\2\252"+
    "\50\0\1\7\1\0\1\7\1\56\14\0\1\7\1\252"+
    "\1\253\2\7\17\0\12\7\1\0\4\7\10\0\1\7"+
    "\1\0\1\7\1\56\14\0\1\7\1\0\3\7\17\0"+
    "\5\7\1\254\4\7\1\0\4\7\10\0\1\7\1\0"+
    "\1\7\1\56\14\0\1\7\1\0\3\7\17\0\1\7"+
    "\1\255\10\7\1\0\4\7\10\0\1\7\1\0\1\7"+
    "\1\56\14\0\1\7\1\0\3\7\17\0\2\7\1\256"+
    "\7\7\1\0\4\7\10\0\1\7\1\0\1\7\1\56"+
    "\14\0\1\7\1\0\2\7\1\257\17\0\12\7\1\0"+
    "\4\7\33\0\1\260\47\0\1\7\1\0\1\7\1\56"+
    "\14\0\1\7\1\0\1\7\1\261\1\7\17\0\12\7"+
    "\1\0\4\7\57\0\1\262\23\0\1\7\1\0\1\7"+
    "\1\56\14\0\1\7\1\0\3\7\17\0\3\7\1\263"+
    "\6\7\1\0\4\7\34\0\1\264\46\0\1\7\1\0"+
    "\1\7\1\56\14\0\1\7\1\0\2\7\1\265\17\0"+
    "\12\7\1\0\4\7\56\0\1\266\24\0\1\7\1\0"+
    "\1\7\1\56\14\0\1\7\1\0\3\7\17\0\2\7"+
    "\1\267\7\7\1\0\4\7\10\0\1\7\1\0\1\7"+
    "\1\56\14\0\1\7\1\0\3\7\17\0\2\7\1\270"+
    "\7\7\1\0\4\7\10\0\1\7\1\0\1\7\1\56"+
    "\14\0\1\7\1\0\3\7\17\0\2\7\1\271\7\7"+
    "\1\0\4\7\61\0\1\272\21\0\1\7\1\0\1\7"+
    "\1\56\14\0\1\7\1\0\3\7\17\0\5\7\1\273"+
    "\4\7\1\0\4\7\33\0\1\274\47\0\1\7\1\0"+
    "\1\7\1\56\14\0\1\7\1\0\1\7\1\275\1\7"+
    "\17\0\12\7\1\0\4\7\10\0\1\7\1\0\1\7"+
    "\1\56\14\0\1\7\1\0\2\7\1\276\17\0\12\7"+
    "\1\0\4\7\55\0\1\277\25\0\1\7\1\0\1\7"+
    "\1\56\14\0\1\7\1\0\3\7\17\0\1\7\1\300"+
    "\10\7\1\0\4\7\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7965];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\10\2\11\1\1\1\11\2\1\1\11\14\1"+
    "\1\11\6\1\6\11\5\1\1\11\1\1\3\11\5\0"+
    "\1\1\1\0\2\11\1\1\2\0\3\1\1\0\2\1"+
    "\12\11\13\1\1\11\1\0\1\11\1\1\1\11\4\0"+
    "\3\1\1\0\13\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\11\2\0\3\1\1\0\6\1\1\0\3\1\1\11"+
    "\1\1\1\0\1\1\3\0\2\1\1\0\5\1\1\11"+
    "\1\1\1\0\1\1\1\0\1\1\1\11\1\1\2\0"+
    "\1\11\2\1\1\0\5\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\5\1\1\11\1\1\1\0\1\1"+
    "\1\0\1\1\1\11\3\1\1\11\1\1\1\0\2\1"+
    "\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[192];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public ArrayList<error> listaErrores = new ArrayList(); // Lista para almacenar errores.
    public ArrayList<lexema> listaLexemas = new ArrayList(); // Lista para almacenar el flujo de palabras (tokens).
    public String cadena ="";
    public boolean flag = false;
    public boolean flagSalto= false;
    public int contadorEtiquetas = 0 ;  // 0 estado yyinitial, 1 estado 0, 2 estado 1;


    public void iniciarCadena()
    {  
        flag = true;
        cadena = "";
    }

    public void finalizarCadena()
    {   
        flagSalto = !flagSalto;     
        Imprimir("--------------------");
        Imprimir(cadena);
        Imprimir("--------------------");
        cadena = "";        
        flag = false;        
    }
    
    public void adderror(int linea, int columna, String valor)
    {        
        singlenton.addErrores(new error("Lexico",valor, linea, columna));
    }
    public void adderror(int linea, int columna, String valor, String desc)
    {        
        singlenton.addErrores(new error("Lexico",linea, columna, valor, desc));
    }    
    public void addLexema(String tipo, String valor, int linea, int columna)
    {        
        listaLexemas.add(new lexema(tipo, valor, linea, columna));	            
    } 

    public void Imprimir(String cadena)
    {
        System.out.println(cadena);
    }    
 



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scannerfs(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { 	return new Symbol(sym.EOF);    
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Caracter ilegal: " + yytext()+" Linea : "+yyline +" Columna: "+yychar); 
                    adderror(yyline, yychar, yytext());
            } 
            // fall through
          case 59: break;
          case 2: 
            { //Imprimir("Salto de linea");
            } 
            // fall through
          case 60: break;
          case 3: 
            { addLexema("Entero", yytext(), yyline, yychar);  	        
                return new Symbol(sym.entero, yychar, yyline, Integer.parseInt(yytext()));
            } 
            // fall through
          case 61: break;
          case 4: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
                return new Symbol(sym.punto, yychar, yyline, yytext());
            } 
            // fall through
          case 62: break;
          case 5: 
            { addLexema("Identificador", yytext(), yyline, yychar);  	        
                return new Symbol(sym.identificador, yychar, yyline, yytext().toLowerCase());
            } 
            // fall through
          case 63: break;
          case 6: 
            { yychar=0;
            } 
            // fall through
          case 64: break;
          case 7: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.div, yychar, yyline, yytext());
            } 
            // fall through
          case 65: break;
          case 8: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.multi, yychar, yyline, yytext());
            } 
            // fall through
          case 66: break;
          case 9: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.suma, yychar, yyline, yytext());
            } 
            // fall through
          case 67: break;
          case 10: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.resta, yychar, yyline, yytext());
            } 
            // fall through
          case 68: break;
          case 11: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.potencia, yychar, yyline, yytext());
            } 
            // fall through
          case 69: break;
          case 12: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.exclam, yychar, yyline, yytext());
            } 
            // fall through
          case 70: break;
          case 13: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.igual, yychar, yyline, yytext());
            } 
            // fall through
          case 71: break;
          case 14: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.mayor, yychar, yyline, yytext());
            } 
            // fall through
          case 72: break;
          case 15: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.menor, yychar, yyline, yytext());
            } 
            // fall through
          case 73: break;
          case 16: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.pari, yychar, yyline, yytext());
            } 
            // fall through
          case 74: break;
          case 17: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.pard, yychar, yyline, yytext());
            } 
            // fall through
          case 75: break;
          case 18: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.corchetei, yychar, yyline, yytext());
            } 
            // fall through
          case 76: break;
          case 19: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.corcheted, yychar, yyline, yytext());
            } 
            // fall through
          case 77: break;
          case 20: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.interrogacion, yychar, yyline, yytext());
            } 
            // fall through
          case 78: break;
          case 21: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.coma, yychar, yyline, yytext());
            } 
            // fall through
          case 79: break;
          case 22: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
                return new Symbol(sym.puntocoma, yychar, yyline, yytext());
            } 
            // fall through
          case 80: break;
          case 23: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
                return new Symbol(sym.llaveI, yychar, yyline, yytext());
            } 
            // fall through
          case 81: break;
          case 24: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
                return new Symbol(sym.llaveD, yychar, yyline, yytext());
            } 
            // fall through
          case 82: break;
          case 25: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
                return new Symbol(sym.dospuntos, yychar, yyline, yytext());
            } 
            // fall through
          case 83: break;
          case 26: 
            { Imprimir(yytext());
            } 
            // fall through
          case 84: break;
          case 27: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.divigual, yychar, yyline, yytext());
            } 
            // fall through
          case 85: break;
          case 28: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.multiigual, yychar, yyline, yytext());
            } 
            // fall through
          case 86: break;
          case 29: 
            { addLexema("reservada", yytext(), yyline, yychar);
                return  new Symbol(sym.si, yychar, yyline, yytext());
            } 
            // fall through
          case 87: break;
          case 30: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.aumento, yychar, yyline, yytext());
            } 
            // fall through
          case 88: break;
          case 31: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.masigual, yychar, yyline, yytext());
            } 
            // fall through
          case 89: break;
          case 32: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.decremento, yychar, yyline, yytext());
            } 
            // fall through
          case 90: break;
          case 33: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.menosigual, yychar, yyline, yytext());
            } 
            // fall through
          case 91: break;
          case 34: 
            { addLexema("|reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.or, yychar, yyline, yytext());
            } 
            // fall through
          case 92: break;
          case 35: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.and, yychar, yyline, yytext());
            } 
            // fall through
          case 93: break;
          case 36: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.desigual, yychar, yyline, yytext());
            } 
            // fall through
          case 94: break;
          case 37: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.igualigual, yychar, yyline, yytext());
            } 
            // fall through
          case 95: break;
          case 38: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.mayorigual, yychar, yyline, yytext());
            } 
            // fall through
          case 96: break;
          case 39: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.menorigual, yychar, yyline, yytext());
            } 
            // fall through
          case 97: break;
          case 40: 
            { addLexema("Decimal", yytext(), yyline, yychar);  	        
                return new Symbol(sym.decimal, yychar, yyline, Double.parseDouble(yytext()));
            } 
            // fall through
          case 98: break;
          case 41: 
            { addLexema("Cadena", yytext(), yyline, yychar);  	        
                return new Symbol(sym.cadena, yychar, yyline, yytext().substring(1, yytext().length()-1));
            } 
            // fall through
          case 99: break;
          case 42: 
            { addLexema("caracter", yytext(), yyline, yychar);  	        
                return new Symbol(sym.cadena, yychar, yyline, yytext().substring(1, yytext().length()-1));
            } 
            // fall through
          case 100: break;
          case 43: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.var, yychar, yyline, yytext());
            } 
            // fall through
          case 101: break;
          case 44: 
            { addLexema("reservada", yytext(), yyline, yychar);  	        
                return new Symbol(sym.para, yychar, yyline, yytext());
            } 
            // fall through
          case 102: break;
          case 45: 
            { addLexema("reservada", yytext(), yyline, yychar);
                return  new Symbol(sym.sino, yychar, yyline, yytext());
            } 
            // fall through
          case 103: break;
          case 46: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.nulo, yychar, yyline, yytext());
            } 
            // fall through
          case 104: break;
          case 47: 
            { addLexema("reservada", yytext(), yyline, yychar);  	        
                return new Symbol(sym.caso, yychar, yyline, yytext());
            } 
            // fall through
          case 105: break;
          case 48: 
            { addLexema("false", yytext(), yyline, yychar);  	        
                return new Symbol(sym.falso, yychar, yyline, false);
            } 
            // fall through
          case 106: break;
          case 49: 
            { addLexema("reservada", yytext(), yyline, yychar);  	        
                return new Symbol(sym.mientras, yychar, yyline, yytext());
            } 
            // fall through
          case 107: break;
          case 50: 
            { addLexema("reservada", yytext(), yyline, yychar);  	        
                return new Symbol(sym.seleccion, yychar, yyline, yytext());
            } 
            // fall through
          case 108: break;
          case 51: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.detener, yychar, yyline, yytext());
            } 
            // fall through
          case 109: break;
          case 52: 
            { addLexema("reservada", yytext(), yyline, yychar);  	        
                return new Symbol(sym.defecto, yychar, yyline, yytext());
            } 
            // fall through
          case 110: break;
          case 53: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.funcion, yychar, yyline, yytext());
            } 
            // fall through
          case 111: break;
          case 54: 
            { addLexema("reservada", yytext(), yyline, yychar);  	        
                return new Symbol(sym.imprimir, yychar, yyline, yytext());
            } 
            // fall through
          case 112: break;
          case 55: 
            { addLexema("reservada", yytext(), yyline, yychar);    
                //System.out.println("------------------------------retornar-------------------");        
                return  new Symbol(sym.retornar, yychar, yyline, yytext());
            } 
            // fall through
          case 113: break;
          case 56: 
            { addLexema("reservada", yytext(), yyline, yychar);            
                return  new Symbol(sym.tcontinuar, yychar, yyline, yytext());
            } 
            // fall through
          case 114: break;
          case 57: 
            { addLexema("true", yytext(), yyline, yychar);  	        
                return new Symbol(sym.verdadero, yychar, yyline, true);
            } 
            // fall through
          case 115: break;
          case 58: 
            { addLexema("reservada", yytext(), yyline, yychar);  	        
                return new Symbol(sym.selecciona, yychar, yyline, yytext());
            } 
            // fall through
          case 116: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
