
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis.XML;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int slash = 4;
  public static final int tcursiva = 38;
  public static final int igualigual = 55;
  public static final int tnegrita = 24;
  public static final int tpath = 40;
  public static final int tminimo = 28;
  public static final int tinicial = 12;
  public static final int listadatos = 36;
  public static final int coma = 45;
  public static final int treferencia = 33;
  public static final int igual = 5;
  public static final int contenedor = 20;
  public static final int tid = 8;
  public static final int ttamanio = 23;
  public static final int llavei = 7;
  public static final int tautoreproduccion = 41;
  public static final int llaved = 6;
  public static final int mayorque = 3;
  public static final int taccion = 32;
  public static final int tmaximo = 27;
  public static final int tcolor = 11;
  public static final int numero = 44;
  public static final int defecto = 34;
  public static final int pari = 56;
  public static final int menos = 47;
  public static final int pard = 57;
  public static final int EOF = 0;
  public static final int mas = 46;
  public static final int tfinal = 39;
  public static final int verdadero = 19;
  public static final int error = 1;
  public static final int talto = 37;
  public static final int tcontrol = 26;
  public static final int or = 50;
  public static final int menorigual = 53;
  public static final int menorque = 2;
  public static final int ttexto = 25;
  public static final int potencia = 49;
  public static final int id = 43;
  public static final int falso = 18;
  public static final int tborde = 17;
  public static final int tfuente = 22;
  public static final int multi = 48;
  public static final int tenviar = 30;
  public static final int mayorigual = 52;
  public static final int dato = 35;
  public static final int tboton = 31;
  public static final int diferente = 54;
  public static final int and = 51;
  public static final int tnombre = 21;
  public static final int tmultimedia = 29;
  public static final int timportar = 10;
  public static final int ty = 15;
  public static final int tventana = 13;
  public static final int tx = 14;
  public static final int tancho = 16;
  public static final int cadena = 42;
  public static final int ttipo = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "menorque",
  "mayorque",
  "slash",
  "igual",
  "llaved",
  "llavei",
  "tid",
  "ttipo",
  "timportar",
  "tcolor",
  "tinicial",
  "tventana",
  "tx",
  "ty",
  "tancho",
  "tborde",
  "falso",
  "verdadero",
  "contenedor",
  "tnombre",
  "tfuente",
  "ttamanio",
  "tnegrita",
  "ttexto",
  "tcontrol",
  "tmaximo",
  "tminimo",
  "tmultimedia",
  "tenviar",
  "tboton",
  "taccion",
  "treferencia",
  "defecto",
  "dato",
  "listadatos",
  "talto",
  "tcursiva",
  "tfinal",
  "tpath",
  "tautoreproduccion",
  "cadena",
  "id",
  "numero",
  "coma",
  "mas",
  "menos",
  "multi",
  "potencia",
  "or",
  "and",
  "mayorigual",
  "menorigual",
  "diferente",
  "igualigual",
  "pari",
  "pard"
  };
}

