
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis.XML;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int slash = 4;
  public static final int tcursiva = 39;
  public static final int tnegrita = 24;
  public static final int tminimo = 29;
  public static final int tinicial = 12;
  public static final int listadatos = 37;
  public static final int treferencia = 34;
  public static final int igual = 5;
  public static final int contenedor = 20;
  public static final int tid = 8;
  public static final int ttamanio = 23;
  public static final int llavei = 7;
  public static final int llaved = 6;
  public static final int mayorque = 3;
  public static final int taccion = 33;
  public static final int tmaximo = 28;
  public static final int tcolor = 11;
  public static final int numero = 45;
  public static final int defecto = 35;
  public static final int EOF = 0;
  public static final int trecursiva = 25;
  public static final int tfinal = 40;
  public static final int verdadero = 19;
  public static final int error = 1;
  public static final int talto = 38;
  public static final int tcontrol = 27;
  public static final int menorque = 2;
  public static final int ttexto = 26;
  public static final int id = 44;
  public static final int falso = 18;
  public static final int tborde = 17;
  public static final int tfuente = 22;
  public static final int tenviar = 31;
  public static final int path = 41;
  public static final int dato = 36;
  public static final int tboton = 32;
  public static final int tnombre = 21;
  public static final int tmultimedia = 30;
  public static final int autoreproduccion = 42;
  public static final int timportar = 10;
  public static final int ty = 15;
  public static final int tventana = 13;
  public static final int tx = 14;
  public static final int tancho = 16;
  public static final int cadena = 43;
  public static final int ttipo = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "menorque",
  "mayorque",
  "slash",
  "igual",
  "llaved",
  "llavei",
  "tid",
  "ttipo",
  "timportar",
  "tcolor",
  "tinicial",
  "tventana",
  "tx",
  "ty",
  "tancho",
  "tborde",
  "falso",
  "verdadero",
  "contenedor",
  "tnombre",
  "tfuente",
  "ttamanio",
  "tnegrita",
  "trecursiva",
  "ttexto",
  "tcontrol",
  "tmaximo",
  "tminimo",
  "tmultimedia",
  "tenviar",
  "tboton",
  "taccion",
  "treferencia",
  "defecto",
  "dato",
  "listadatos",
  "talto",
  "tcursiva",
  "tfinal",
  "path",
  "autoreproduccion",
  "cadena",
  "id",
  "numero"
  };
}

