
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis.Gdato;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int id = 7;
  public static final int cadena = 8;
  public static final int mayorque = 3;
  public static final int slash = 4;
  public static final int EOF = 0;
  public static final int numero = 9;
  public static final int lista = 6;
  public static final int principal = 5;
  public static final int error = 1;
  public static final int menorque = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "menorque",
  "mayorque",
  "slash",
  "principal",
  "lista",
  "id",
  "cadena",
  "numero"
  };
}

